In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('telecom_churn.csv')

In [3]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [5]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
df['TotalCharges'].value_counts()

          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: TotalCharges, Length: 6531, dtype: int64

In [7]:
df["TotalCharges"].replace(" ",np.nan,inplace=True)


In [8]:
df["TotalCharges"]=df["TotalCharges"].astype("float")


In [9]:
df["TotalCharges"].fillna(df["TotalCharges"].mean(),inplace=True)


In [10]:
df["TotalCharges"].value_counts()

2283.300441    11
20.200000      11
19.750000       9
20.050000       8
19.900000       8
               ..
6849.400000     1
692.350000      1
130.150000      1
3211.900000     1
6844.500000     1
Name: TotalCharges, Length: 6531, dtype: int64

In [11]:


#separate all object type data and hold in df_cat
df_cat = df.select_dtypes("object")
#separate all numeric datatype type data and hold in df_num
df_num=df.select_dtypes(["float64","int64"])



In [12]:
from sklearn.preprocessing import LabelEncoder
for col in df_cat:
    #create object of LabelEncoder
    le=LabelEncoder()
    df_cat[col] = le.fit_transform(df_cat[col])

In [13]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   int64
 1   gender            7043 non-null   int64
 2   Partner           7043 non-null   int64
 3   Dependents        7043 non-null   int64
 4   PhoneService      7043 non-null   int64
 5   MultipleLines     7043 non-null   int64
 6   InternetService   7043 non-null   int64
 7   OnlineSecurity    7043 non-null   int64
 8   OnlineBackup      7043 non-null   int64
 9   DeviceProtection  7043 non-null   int64
 10  TechSupport       7043 non-null   int64
 11  StreamingTV       7043 non-null   int64
 12  StreamingMovies   7043 non-null   int64
 13  Contract          7043 non-null   int64
 14  PaperlessBilling  7043 non-null   int64
 15  PaymentMethod     7043 non-null   int64
 16  Churn             7043 non-null   int64
dtypes: int64(17)
memory usage: 935.5 

In [14]:
df_new = pd.concat([df_num,df_cat],axis=1)
df_new.head()



SeniorCitizen  tenure  MonthlyCharges  TotalCharges  customerID  gender  \
0              0       1           29.85         29.85        5375       0   
1              0      34           56.95       1889.50        3962       1   
2              0       2           53.85        108.15        2564       1   
3              0      45           42.30       1840.75        5535       1   
4              0       2           70.70        151.65        6511       0   

   Partner  Dependents  PhoneService  MultipleLines  ...  OnlineSecurity  \
0        1           0             0              1  ...               0   
1        0           0             1              0  ...               2   
2        0           0             1              0  ...               2   
3        0           0             0              1  ...               2   
4        0           0             1              0  ...               0   

   OnlineBackup  DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0             2                 0            0            0                0   
1             0                 2            0            0                0   
2             2                 0            0            0                0   
3             0                 2            2            0                0   
4             0                 0            0            0                0   

   Contract  PaperlessBilling  PaymentMethod  Churn  
0         0                 1              2      0  
1         1                 0              3      0  
2         0                 1              3      1  
3         1                 0              0      0  
4         0                 1              2      1  

[5 rows x 21 columns]

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
X=df_new.drop("Churn",axis=1) #input variable
Y=df_new["Churn"] #output means target

In [17]:


from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)



In [18]:
pd.Series(Y_train).value_counts()

0    3589
1    1341
Name: Churn, dtype: int64

In [19]:
from imblearn.over_sampling import RandomOverSampler

In [20]:


ros=RandomOverSampler()



In [21]:
X_train,Y_train=ros.fit_resample(X_train,Y_train)

In [22]:
test1=ros.fit_resample(X_test,Y_test)

In [23]:
pd.Series(Y_train).value_counts()

0    3589
1    3589
Name: Churn, dtype: int64

In [24]:


ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)



In [25]:


def create_model(model):
    model.fit(X_train,Y_train)
    Y_pred=model.predict(X_test)
    print("Classification report")
    print(classification_report(Y_test,Y_pred))
    print("Confusion Matrix")
    print(confusion_matrix(Y_test,Y_pred))
    return model



In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


In [27]:


lr=LogisticRegression()



In [28]:
lr=create_model(lr)

Classification report
              precision    recall  f1-score   support

           0       0.92      0.73      0.82      1585
           1       0.50      0.82      0.62       528

    accuracy                           0.75      2113
   macro avg       0.71      0.78      0.72      2113
weighted avg       0.82      0.75      0.77      2113

Confusion Matrix
[[1161  424]
 [  96  432]]


In [29]:

from sklearn.tree import DecisionTreeClassifier



In [30]:
dt=DecisionTreeClassifier()

In [31]:
dt=create_model(dt)

Classification report
              precision    recall  f1-score   support

           0       0.83      0.81      0.82      1585
           1       0.47      0.50      0.49       528

    accuracy                           0.74      2113
   macro avg       0.65      0.66      0.66      2113
weighted avg       0.74      0.74      0.74      2113

Confusion Matrix
[[1289  296]
 [ 262  266]]


In [32]:
dt1=DecisionTreeClassifier(max_depth=3)

In [33]:
dt1=create_model(dt1)

Classification report
              precision    recall  f1-score   support

           0       0.92      0.69      0.79      1585
           1       0.47      0.82      0.60       528

    accuracy                           0.73      2113
   macro avg       0.70      0.76      0.69      2113
weighted avg       0.81      0.73      0.74      2113

Confusion Matrix
[[1099  486]
 [  95  433]]


In [34]:
dt2=DecisionTreeClassifier(min_samples_leaf=50)

In [35]:
dt2=create_model(dt2)

Classification report
              precision    recall  f1-score   support

           0       0.91      0.72      0.80      1585
           1       0.48      0.78      0.60       528

    accuracy                           0.74      2113
   macro avg       0.70      0.75      0.70      2113
weighted avg       0.80      0.74      0.75      2113

Confusion Matrix
[[1144  441]
 [ 115  413]]


In [36]:
dt3=DecisionTreeClassifier(criterion="entropy",min_samples_leaf=50)


In [37]:


dt3=create_model(dt3)



Classification report
              precision    recall  f1-score   support

           0       0.91      0.73      0.81      1585
           1       0.49      0.78      0.60       528

    accuracy                           0.74      2113
   macro avg       0.70      0.76      0.71      2113
weighted avg       0.80      0.74      0.76      2113

Confusion Matrix
[[1154  431]
 [ 115  413]]


In [38]:
from sklearn.ensemble import VotingClassifier

In [39]:


lr=LogisticRegression()
dt=DecisionTreeClassifier()
dt1=DecisionTreeClassifier(criterion="entropy",min_samples_leaf=50)



In [40]:
model_list=[("LogisticRegression",lr),("DecisionTreeClassifier",dt),("DecisionTreeClassifierwithentropy",dt1)]


In [41]:
vc=VotingClassifier(estimators=model_list)

In [42]:
vc=create_model(vc)

Classification report
              precision    recall  f1-score   support

           0       0.91      0.76      0.83      1585
           1       0.52      0.78      0.62       528

    accuracy                           0.76      2113
   macro avg       0.71      0.77      0.72      2113
weighted avg       0.81      0.76      0.78      2113

Confusion Matrix
[[1200  385]
 [ 117  411]]


In [43]:
vc1=VotingClassifier(estimators=model_list,voting="soft")

In [44]:
vc1=create_model(vc1)

Classification report
              precision    recall  f1-score   support

           0       0.87      0.81      0.84      1585
           1       0.53      0.64      0.58       528

    accuracy                           0.77      2113
   macro avg       0.70      0.73      0.71      2113
weighted avg       0.79      0.77      0.78      2113

Confusion Matrix
[[1289  296]
 [ 191  337]]


In [45]:


from sklearn.ensemble import BaggingClassifier



In [46]:
bc=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=7043,random_state=1)

In [47]:
bc=create_model(bc)


Classification report
              precision    recall  f1-score   support

           0       0.92      0.74      0.82      1585
           1       0.51      0.82      0.63       528

    accuracy                           0.76      2113
   macro avg       0.72      0.78      0.72      2113
weighted avg       0.82      0.76      0.77      2113

Confusion Matrix
[[1165  420]
 [  95  433]]


In [48]:
bc1=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=7043,random_state=1,bootstrap=False)

In [49]:
bc1=create_model(bc1)

Classification report
              precision    recall  f1-score   support

           0       0.92      0.73      0.82      1585
           1       0.50      0.82      0.62       528

    accuracy                           0.75      2113
   macro avg       0.71      0.77      0.72      2113
weighted avg       0.82      0.75      0.77      2113

Confusion Matrix
[[1160  425]
 [  97  431]]


In [50]:
bc2=BaggingClassifier(DecisionTreeClassifier(),n_estimators=10,max_samples=7043,random_state=1) #RandomForestTree

In [51]:
bc2=create_model(bc2) 

Classification report
              precision    recall  f1-score   support

           0       0.86      0.85      0.85      1585
           1       0.56      0.57      0.56       528

    accuracy                           0.78      2113
   macro avg       0.71      0.71      0.71      2113
weighted avg       0.78      0.78      0.78      2113

Confusion Matrix
[[1350  235]
 [ 228  300]]


In [52]:
from sklearn.ensemble import AdaBoostClassifier

In [53]:
ada=AdaBoostClassifier(n_estimators=75)

In [54]:
ada=create_model(ada)

Classification report
              precision    recall  f1-score   support

           0       0.92      0.73      0.81      1585
           1       0.50      0.80      0.61       528

    accuracy                           0.75      2113
   macro avg       0.71      0.77      0.71      2113
weighted avg       0.81      0.75      0.76      2113

Confusion Matrix
[[1157  428]
 [ 105  423]]


In [55]:
from sklearn.ensemble import GradientBoostingClassifier

In [56]:
gb=GradientBoostingClassifier(n_estimators=75)

In [57]:
gb=create_model(gb)

Classification report
              precision    recall  f1-score   support

           0       0.92      0.73      0.81      1585
           1       0.50      0.81      0.62       528

    accuracy                           0.75      2113
   macro avg       0.71      0.77      0.72      2113
weighted avg       0.82      0.75      0.77      2113

Confusion Matrix
[[1158  427]
 [ 100  428]]


In [58]:
from xgboost import XGBClassifier

In [59]:
xgb=XGBClassifier(n_estimators=75,reg_alpha=1)

In [60]:
xgb=create_model(xgb)

[10:59:45] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Classification report
              precision    recall  f1-score   support

           0       0.89      0.81      0.85      1585
           1       0.55      0.68      0.61       528

    accuracy                           0.78      2113
   macro avg       0.72      0.75      0.73      2113
weighted avg       0.80      0.78      0.79      2113

Confusion Matrix
[[1289  296]
 [ 167  361]]


In [61]:
from mlxtend.classifier import StackingClassifier

In [62]:
model_list=[lr,dt,dt1]

In [63]:
meta=LogisticRegression()

In [64]:
sc=StackingClassifier(model_list,meta)

In [65]:
sc=create_model(sc)

Classification report
              precision    recall  f1-score   support

           0       0.83      0.81      0.82      1585
           1       0.47      0.49      0.48       528

    accuracy                           0.73      2113
   macro avg       0.65      0.65      0.65      2113
weighted avg       0.74      0.73      0.74      2113

Confusion Matrix
[[1291  294]
 [ 269  259]]


In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [67]:
knc=KNeighborsClassifier(n_neighbors=7,metric="minkowski",p=2)

In [68]:
knc=create_model(knc)

Classification report
              precision    recall  f1-score   support

           0       0.90      0.66      0.76      1585
           1       0.43      0.78      0.55       528

    accuracy                           0.69      2113
   macro avg       0.66      0.72      0.66      2113
weighted avg       0.78      0.69      0.71      2113

Confusion Matrix
[[1039  546]
 [ 116  412]]


In [69]:
from sklearn.svm import  LinearSVC

In [70]:
svm=LinearSVC(random_state=1)

In [71]:
svm=create_model(svm)

Classification report
              precision    recall  f1-score   support

           0       0.93      0.73      0.81      1585
           1       0.50      0.83      0.62       528

    accuracy                           0.75      2113
   macro avg       0.71      0.78      0.72      2113
weighted avg       0.82      0.75      0.77      2113

Confusion Matrix
[[1150  435]
 [  92  436]]


In [72]:
svm1=LinearSVC(random_state=1,C=0.08)

In [73]:
svm1=create_model(svm1)

Classification report
              precision    recall  f1-score   support

           0       0.93      0.72      0.81      1585
           1       0.50      0.83      0.62       528

    accuracy                           0.75      2113
   macro avg       0.71      0.78      0.72      2113
weighted avg       0.82      0.75      0.77      2113

Confusion Matrix
[[1149  436]
 [  90  438]]


In [75]:

from sklearn.svm import SVC
poly_svc=SVC(random_state=1,kernel="poly")

In [76]:
poly_svc=create_model(poly_svc)

Classification report
              precision    recall  f1-score   support

           0       0.91      0.73      0.81      1585
           1       0.49      0.78      0.60       528

    accuracy                           0.74      2113
   macro avg       0.70      0.75      0.70      2113
weighted avg       0.80      0.74      0.76      2113

Confusion Matrix
[[1152  433]
 [ 116  412]]


In [77]:
# create the object of SVC class
r_svc = SVC(random_state=1,kernel='rbf')
# rbf means radial basis function

In [78]:
r_svc = create_model(r_svc)

Classification report
              precision    recall  f1-score   support

           0       0.91      0.75      0.82      1585
           1       0.50      0.77      0.61       528

    accuracy                           0.75      2113
   macro avg       0.71      0.76      0.71      2113
weighted avg       0.81      0.75      0.77      2113

Confusion Matrix
[[1183  402]
 [ 120  408]]
